//
// Coupons.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Coupons: Codable {

    public var active: String?
    public var couponCode: String?
    public var couponDescription: String?
    public var couponId: Int64?
    public var couponName: String?
    public var couponType: String?
    public var couponValue: Int64?
    public var createdBy: String?
    public var createdOn: Date?
    public var lastUpdateLogin: String?
    public var modifiedBy: String?
    public var modifiedOn: Date?
    public var usageLimit: Int64?
    public var validEndDate: Date?
    public var validStartDate: Date?
    public var versionNumber: Int64?

    public init(active: String?, couponCode: String?, couponDescription: String?, couponId: Int64?, couponName: String?, couponType: String?, couponValue: Int64?, createdBy: String?, createdOn: Date?, lastUpdateLogin: String?, modifiedBy: String?, modifiedOn: Date?, usageLimit: Int64?, validEndDate: Date?, validStartDate: Date?, versionNumber: Int64?) {
        self.active = active
        self.couponCode = couponCode
        self.couponDescription = couponDescription
        self.couponId = couponId
        self.couponName = couponName
        self.couponType = couponType
        self.couponValue = couponValue
        self.createdBy = createdBy
        self.createdOn = createdOn
        self.lastUpdateLogin = lastUpdateLogin
        self.modifiedBy = modifiedBy
        self.modifiedOn = modifiedOn
        self.usageLimit = usageLimit
        self.validEndDate = validEndDate
        self.validStartDate = validStartDate
        self.versionNumber = versionNumber
    }


}

