//
// LoginRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoginRequest: Codable {

    public var firstName: String?
    public var loginSource: String?
    public var password: String?
    public var username: String?

    public init(firstName: String?, loginSource: String?, password: String?, username: String?) {
        self.firstName = firstName
        self.loginSource = loginSource
        self.password = password
        self.username = username
    }


}

