//
// ModelAndView.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ModelAndView: Codable {

//    public enum Status: String, Codable {
//        case _100 CONTINUE = "100 CONTINUE"
//        case _101 SWITCHINGPROTOCOLS = "101 SWITCHING_PROTOCOLS"
//        case _102 PROCESSING = "102 PROCESSING"
//        case _103 CHECKPOINT = "103 CHECKPOINT"
//        case _200 OK = "200 OK"
//        case _201 CREATED = "201 CREATED"
//        case _202 ACCEPTED = "202 ACCEPTED"
//        case _203 NONAUTHORITATIVEINFORMATION = "203 NON_AUTHORITATIVE_INFORMATION"
//        case _204 NOCONTENT = "204 NO_CONTENT"
//        case _205 RESETCONTENT = "205 RESET_CONTENT"
//        case _206 PARTIALCONTENT = "206 PARTIAL_CONTENT"
//        case _207 MULTISTATUS = "207 MULTI_STATUS"
//        case _208 ALREADYREPORTED = "208 ALREADY_REPORTED"
//        case _226 IMUSED = "226 IM_USED"
//        case _300 MULTIPLECHOICES = "300 MULTIPLE_CHOICES"
//        case _301 MOVEDPERMANENTLY = "301 MOVED_PERMANENTLY"
//        case _302 FOUND = "302 FOUND"
//        case _302 MOVEDTEMPORARILY = "302 MOVED_TEMPORARILY"
//        case _303 SEEOTHER = "303 SEE_OTHER"
//        case _304 NOTMODIFIED = "304 NOT_MODIFIED"
//        case _305 USEPROXY = "305 USE_PROXY"
//        case _307 TEMPORARYREDIRECT = "307 TEMPORARY_REDIRECT"
//        case _308 PERMANENTREDIRECT = "308 PERMANENT_REDIRECT"
//        case _400 BADREQUEST = "400 BAD_REQUEST"
//        case _401 UNAUTHORIZED = "401 UNAUTHORIZED"
//        case _402 PAYMENTREQUIRED = "402 PAYMENT_REQUIRED"
//        case _403 FORBIDDEN = "403 FORBIDDEN"
//        case _404 NOTFOUND = "404 NOT_FOUND"
//        case _405 METHODNOTALLOWED = "405 METHOD_NOT_ALLOWED"
//        case _406 NOTACCEPTABLE = "406 NOT_ACCEPTABLE"
//        case _407 PROXYAUTHENTICATIONREQUIRED = "407 PROXY_AUTHENTICATION_REQUIRED"
//        case _408 REQUESTTIMEOUT = "408 REQUEST_TIMEOUT"
//        case _409 CONFLICT = "409 CONFLICT"
//        case _410 GONE = "410 GONE"
//        case _411 LENGTHREQUIRED = "411 LENGTH_REQUIRED"
//        case _412 PRECONDITIONFAILED = "412 PRECONDITION_FAILED"
//        case _413 PAYLOADTOOLARGE = "413 PAYLOAD_TOO_LARGE"
//        case _413 REQUESTENTITYTOOLARGE = "413 REQUEST_ENTITY_TOO_LARGE"
//        case _414 URITOOLONG = "414 URI_TOO_LONG"
//        case _414 REQUESTURITOOLONG = "414 REQUEST_URI_TOO_LONG"
//        case _415 UNSUPPORTEDMEDIATYPE = "415 UNSUPPORTED_MEDIA_TYPE"
//        case _416 REQUESTEDRANGENOTSATISFIABLE = "416 REQUESTED_RANGE_NOT_SATISFIABLE"
//        case _417 EXPECTATIONFAILED = "417 EXPECTATION_FAILED"
//        case _418 IAMATEAPOT = "418 I_AM_A_TEAPOT"
//        case _419 INSUFFICIENTSPACEONRESOURCE = "419 INSUFFICIENT_SPACE_ON_RESOURCE"
//        case _420 METHODFAILURE = "420 METHOD_FAILURE"
//        case _421 DESTINATIONLOCKED = "421 DESTINATION_LOCKED"
//        case _422 UNPROCESSABLEENTITY = "422 UNPROCESSABLE_ENTITY"
//        case _423 LOCKED = "423 LOCKED"
//        case _424 FAILEDDEPENDENCY = "424 FAILED_DEPENDENCY"
//        case _425 TOOEARLY = "425 TOO_EARLY"
//        case _426 UPGRADEREQUIRED = "426 UPGRADE_REQUIRED"
//        case _428 PRECONDITIONREQUIRED = "428 PRECONDITION_REQUIRED"
//        case _429 TOOMANYREQUESTS = "429 TOO_MANY_REQUESTS"
//        case _431 REQUESTHEADERFIELDSTOOLARGE = "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
//        case _451 UNAVAILABLEFORLEGALREASONS = "451 UNAVAILABLE_FOR_LEGAL_REASONS"
//        case _500 INTERNALSERVERERROR = "500 INTERNAL_SERVER_ERROR"
//        case _501 NOTIMPLEMENTED = "501 NOT_IMPLEMENTED"
//        case _502 BADGATEWAY = "502 BAD_GATEWAY"
//        case _503 SERVICEUNAVAILABLE = "503 SERVICE_UNAVAILABLE"
//        case _504 GATEWAYTIMEOUT = "504 GATEWAY_TIMEOUT"
//        case _505 HTTPVERSIONNOTSUPPORTED = "505 HTTP_VERSION_NOT_SUPPORTED"
//        case _506 VARIANTALSONEGOTIATES = "506 VARIANT_ALSO_NEGOTIATES"
//        case _507 INSUFFICIENTSTORAGE = "507 INSUFFICIENT_STORAGE"
//        case _508 LOOPDETECTED = "508 LOOP_DETECTED"
//        case _509 BANDWIDTHLIMITEXCEEDED = "509 BANDWIDTH_LIMIT_EXCEEDED"
//        case _510 NOTEXTENDED = "510 NOT_EXTENDED"
//        case _511 NETWORKAUTHENTICATIONREQUIRED = "511 NETWORK_AUTHENTICATION_REQUIRED"
    public enum Status : String, Codable{
        public typealias RawValue = String

        case _100 = "100 CONTINUE"
        case _101 = "101 SWITCHING_PROTOCOLS"
        case _102 = "102 PROCESSING"
        case _103 = "103 CHECKPOINT"
        case _200 = "200 OK"
        case _201 = "201 CREATED"
        case _202 = "202 ACCEPTED"
        case _203 = "203 NON_AUTHORITATIVE_INFORMATION"
        case _204 = "204 NO_CONTENT"
        case _205 = "205 RESET_CONTENT"
        case _206 = "206 PARTIAL_CONTENT"
        case _207 = "207 MULTI_STATUS"
        case _208 = "208 ALREADY_REPORTED"
        case _226 = "226 IM_USED"
        case _300 = "300 MULTIPLE_CHOICES"
        case _301 = "301 MOVED_PERMANENTLY"
        case _302 = "302 FOUND"
        case _303 = "303 SEE_OTHER"
        case _304 = "304 NOT_MODIFIED"
        case _305 = "305 USE_PROXY"
        case _307 = "307 TEMPORARY_REDIRECT"
        case _308 = "308 PERMANENT_REDIRECT"
        case _400 = "400 BAD_REQUEST"
        case _401 = "401 UNAUTHORIZED"
        case _402 = "402 PAYMENT_REQUIRED"
        case _403 = "403 FORBIDDEN"
        case _404 = "404 NOT_FOUND"
        case _405 = "405 METHOD_NOT_ALLOWED"
        case _406 = "406 NOT_ACCEPTABLE"
        case _407 = "407 PROXY_AUTHENTICATION_REQUIRED"
        case _408 = "408 REQUEST_TIMEOUT"
        case _409 = "409 CONFLICT"
        case _410 = "410 GONE"
        case _411 = "411 LENGTH_REQUIRED"
        case _412 = "412 PRECONDITION_FAILED"
        case _4133 = "413 PAYLOAD_TOO_LARGE"
        case _413 = "413 REQUEST_ENTITY_TOO_LARGE"
        case _4144 = "414 URI_TOO_LONG"
        case _414 = "414 REQUEST_URI_TOO_LONG"
        case _415 = "415 UNSUPPORTED_MEDIA_TYPE"
        case _416 = "416 REQUESTED_RANGE_NOT_SATISFIABLE"
        case _417 = "417 EXPECTATION_FAILED"
        case _418 = "418 I_AM_A_TEAPOT"
        case _419 = "419 INSUFFICIENT_SPACE_ON_RESOURCE"
        case _420 = "420 METHOD_FAILURE"
        case _421 = "421 DESTINATION_LOCKED"
        case _422 = "422 UNPROCESSABLE_ENTITY"
        case _423 = "423 LOCKED"
        case _424 = "424 FAILED_DEPENDENCY"
        case _425 = "425 TOO_EARLY"
        case _426 = "426 UPGRADE_REQUIRED"
        case _428 = "428 PRECONDITION_REQUIRED"
        case _429 = "429 TOO_MANY_REQUESTS"
        case _431 = "431 REQUEST_HEADER_FIELDS_TOO_LARGE"
        case _451 = "451 UNAVAILABLE_FOR_LEGAL_REASONS"
        case _500 = "500 INTERNAL_SERVER_ERROR"
        case _501 = "501 NOT_IMPLEMENTED"
        case _502 = "502 BAD_GATEWAY"
        case _503 = "503 SERVICE_UNAVAILABLE"
        case _504 = "504 GATEWAY_TIMEOUT"
        case _505 = "505 HTTP_VERSION_NOT_SUPPORTED"
        case _506 = "506 VARIANT_ALSO_NEGOTIATES"
        case _507 = "507 INSUFFICIENT_STORAGE"
        case _508 = "508 LOOP_DETECTED"
        case _509 = "509 BANDWIDTH_LIMIT_EXCEEDED"
        case _510 = "510 NOT_EXTENDED"
        case _511 = "511 NETWORK_AUTHENTICATION_REQUIRED"
    }
    public var empty: Bool?
    public var model: JSONValue?
    public var modelMap: [String:JSONValue]?
    public var reference: Bool?
    public var status: Status?
    public var view: View?
    public var viewName: String?

    public init(empty: Bool?, model: JSONValue?, modelMap: [String:JSONValue]?, reference: Bool?, status: Status?, view: View?, viewName: String?) {
        self.empty = empty
        self.model = model
        self.modelMap = modelMap
        self.reference = reference
        self.status = status
        self.view = view
        self.viewName = viewName
    }


}

