//
// MovieContent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MovieContent: Codable {

    public var active: String?
    public var contentDescription: String?
    public var contentKey: String?
    public var contentSource: String?
    public var contentSourceType: String?
    public var contentType: String?
    public var createdBy: String?
    public var createdOn: Date?
    public var lastUpdateLogin: String?
    public var modifiedBy: String?
    public var modifiedOn: Date?
    public var movieContentId: Int64?
    public var movieId: Int64?
    public var secretDataKey: String?
    public var versionNumber: Int64?

    public init(active: String?, contentDescription: String?, contentKey: String?, contentSource: String?, contentSourceType: String?, contentType: String?, createdBy: String?, createdOn: Date?, lastUpdateLogin: String?, modifiedBy: String?, modifiedOn: Date?, movieContentId: Int64?, movieId: Int64?, secretDataKey: String?, versionNumber: Int64?) {
        self.active = active
        self.contentDescription = contentDescription
        self.contentKey = contentKey
        self.contentSource = contentSource
        self.contentSourceType = contentSourceType
        self.contentType = contentType
        self.createdBy = createdBy
        self.createdOn = createdOn
        self.lastUpdateLogin = lastUpdateLogin
        self.modifiedBy = modifiedBy
        self.modifiedOn = modifiedOn
        self.movieContentId = movieContentId
        self.movieId = movieId
        self.secretDataKey = secretDataKey
        self.versionNumber = versionNumber
    }


}

