//
// PlayMovieRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PlayMovieRequest: Codable {

    public var ipAddress: String?
    public var movieId: Int64?

    public init(ipAddress: String?, movieId: Int64?) {
        self.ipAddress = ipAddress
        self.movieId = movieId
    }


}

