//
// QuickDashboard.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct QuickDashboard: Codable {

    public var amtOfPaidOrders: Int64?
    public var amtOfPaypalOrders: Int64?
    public var amtOfTaxOrders: Int64?
    public var hrsPlayed: Int64?
    public var _id: Int64?
    public var noOfMovies: Int64?
    public var noOfNowStreaming: Int64?
    public var noOfPaidOrders: Int64?
    public var noOfUpcomingMovies: Int64?
    public var noOfUsers: Int64?

    public init(amtOfPaidOrders: Int64?, amtOfPaypalOrders: Int64?, amtOfTaxOrders: Int64?, hrsPlayed: Int64?, _id: Int64?, noOfMovies: Int64?, noOfNowStreaming: Int64?, noOfPaidOrders: Int64?, noOfUpcomingMovies: Int64?, noOfUsers: Int64?) {
        self.amtOfPaidOrders = amtOfPaidOrders
        self.amtOfPaypalOrders = amtOfPaypalOrders
        self.amtOfTaxOrders = amtOfTaxOrders
        self.hrsPlayed = hrsPlayed
        self._id = _id
        self.noOfMovies = noOfMovies
        self.noOfNowStreaming = noOfNowStreaming
        self.noOfPaidOrders = noOfPaidOrders
        self.noOfUpcomingMovies = noOfUpcomingMovies
        self.noOfUsers = noOfUsers
    }

    public enum CodingKeys: String, CodingKey { 
        case amtOfPaidOrders
        case amtOfPaypalOrders
        case amtOfTaxOrders
        case hrsPlayed
        case _id = "id"
        case noOfMovies
        case noOfNowStreaming
        case noOfPaidOrders
        case noOfUpcomingMovies
        case noOfUsers
    }


}

