//
// Subtitles.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Subtitles: Codable {

    public var active: String?
    public var createdBy: String?
    public var createdOn: Date?
    public var _description: String?
    public var language: String?
    public var lastUpdateLogin: String?
    public var modifiedBy: String?
    public var modifiedOn: Date?
    public var movieId: Int64?
    public var name: String?
    public var ordering: Int64?
    public var subType: String?
    public var subUrl: String?
    public var subtitleId: Int64?
    public var versionNumber: Int64?

    public init(active: String?, createdBy: String?, createdOn: Date?, _description: String?, language: String?, lastUpdateLogin: String?, modifiedBy: String?, modifiedOn: Date?, movieId: Int64?, name: String?, ordering: Int64?, subType: String?, subUrl: String?, subtitleId: Int64?, versionNumber: Int64?) {
        self.active = active
        self.createdBy = createdBy
        self.createdOn = createdOn
        self._description = _description
        self.language = language
        self.lastUpdateLogin = lastUpdateLogin
        self.modifiedBy = modifiedBy
        self.modifiedOn = modifiedOn
        self.movieId = movieId
        self.name = name
        self.ordering = ordering
        self.subType = subType
        self.subUrl = subUrl
        self.subtitleId = subtitleId
        self.versionNumber = versionNumber
    }

    public enum CodingKeys: String, CodingKey { 
        case active
        case createdBy
        case createdOn
        case _description = "description"
        case language
        case lastUpdateLogin
        case modifiedBy
        case modifiedOn
        case movieId
        case name
        case ordering
        case subType
        case subUrl
        case subtitleId
        case versionNumber
    }


}

