//
// ToggleFeaturedMovieRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ToggleFeaturedMovieRequest: Codable {

    public var featuredStatus: String?

    public init(featuredStatus: String?) {
        self.featuredStatus = featuredStatus
    }


}

