//
// ToggleActiveMovieRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ToggleActiveMovieRequest: Codable {

    public var activeStatus: String?

    public init(activeStatus: String?) {
        self.activeStatus = activeStatus
    }


}

