//
// FaqGroups.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FaqGroups: Codable {

    public var active: String?
    public var createdBy: String?
    public var createdOn: Date?
    public var _description: String?
    public var faqs: [Faqs]?
    public var groupName: String?
    public var _id: Int64?
    public var lastUpdateLogin: String?
    public var modifiedBy: String?
    public var modifiedOn: Date?
    public var ordering: Int64?
    public var versionNumber: Int64?

    public init(active: String?, createdBy: String?, createdOn: Date?, _description: String?, faqs: [Faqs]?, groupName: String?, _id: Int64?, lastUpdateLogin: String?, modifiedBy: String?, modifiedOn: Date?, ordering: Int64?, versionNumber: Int64?) {
        self.active = active
        self.createdBy = createdBy
        self.createdOn = createdOn
        self._description = _description
        self.faqs = faqs
        self.groupName = groupName
        self._id = _id
        self.lastUpdateLogin = lastUpdateLogin
        self.modifiedBy = modifiedBy
        self.modifiedOn = modifiedOn
        self.ordering = ordering
        self.versionNumber = versionNumber
    }

    public enum CodingKeys: String, CodingKey { 
        case active
        case createdBy
        case createdOn
        case _description = "description"
        case faqs
        case groupName
        case _id = "id"
        case lastUpdateLogin
        case modifiedBy
        case modifiedOn
        case ordering
        case versionNumber
    }


}

