//
// MovieCouponValidateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MovieCouponValidateRequest: Codable {

    public var couponCode: String?
    public var movieId: Int64?

    public init(couponCode: String?, movieId: Int64?) {
        self.couponCode = couponCode
        self.movieId = movieId
    }


}

