//
// MovieCrew.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MovieCrew: Codable {

    public var active: String?
    public var actor: Actors?
    public var createdBy: String?
    public var createdOn: Date?
    public var crewId: Int64?
    public var crewRole: String?
    public var lastUpdateLogin: String?
    public var modifiedBy: String?
    public var modifiedOn: Date?
    public var movieCrewId: Int64?
    public var movieId: Int64?
    public var ordering: Int64?
    public var versionNumber: Int64?

    public init(active: String?, actor: Actors?, createdBy: String?, createdOn: Date?, crewId: Int64?, crewRole: String?, lastUpdateLogin: String?, modifiedBy: String?, modifiedOn: Date?, movieCrewId: Int64?, movieId: Int64?, ordering: Int64?, versionNumber: Int64?) {
        self.active = active
        self.actor = actor
        self.createdBy = createdBy
        self.createdOn = createdOn
        self.crewId = crewId
        self.crewRole = crewRole
        self.lastUpdateLogin = lastUpdateLogin
        self.modifiedBy = modifiedBy
        self.modifiedOn = modifiedOn
        self.movieCrewId = movieCrewId
        self.movieId = movieId
        self.ordering = ordering
        self.versionNumber = versionNumber
    }


}

