//
// MovieReviews.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MovieReviews: Codable {

    public var active: String?
    public var createdBy: String?
    public var createdOn: Date?
    public var lastUpdateLogin: String?
    public var modifiedBy: String?
    public var modifiedOn: Date?
    public var movieId: Int64?
    public var movieReviewId: Int64?
    public var rating: String?
    public var reviewComments: String?
    public var user: Users?
    public var userId: Int64?
    public var versionNumber: Int64?

    public init(active: String?, createdBy: String?, createdOn: Date?, lastUpdateLogin: String?, modifiedBy: String?, modifiedOn: Date?, movieId: Int64?, movieReviewId: Int64?, rating: String?, reviewComments: String?, user: Users?, userId: Int64?, versionNumber: Int64?) {
        self.active = active
        self.createdBy = createdBy
        self.createdOn = createdOn
        self.lastUpdateLogin = lastUpdateLogin
        self.modifiedBy = modifiedBy
        self.modifiedOn = modifiedOn
        self.movieId = movieId
        self.movieReviewId = movieReviewId
        self.rating = rating
        self.reviewComments = reviewComments
        self.user = user
        self.userId = userId
        self.versionNumber = versionNumber
    }


}

