//
// MovieCollections.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MovieCollections: Codable {

    public var active: String?
    public var collectionId: Int64?
    public var createdBy: String?
    public var createdOn: Date?
    public var _id: Int64?
    public var lastUpdateLogin: String?
    public var modifiedBy: String?
    public var modifiedOn: Date?
    public var movie: Movies?
    public var movieId: Int64?
    public var ordering: Int64?
    public var versionNumber: Int64?

    public init(active: String?, collectionId: Int64?, createdBy: String?, createdOn: Date?, _id: Int64?, lastUpdateLogin: String?, modifiedBy: String?, modifiedOn: Date?, movie: Movies?, movieId: Int64?, ordering: Int64?, versionNumber: Int64?) {
        self.active = active
        self.collectionId = collectionId
        self.createdBy = createdBy
        self.createdOn = createdOn
        self._id = _id
        self.lastUpdateLogin = lastUpdateLogin
        self.modifiedBy = modifiedBy
        self.modifiedOn = modifiedOn
        self.movie = movie
        self.movieId = movieId
        self.ordering = ordering
        self.versionNumber = versionNumber
    }

    public enum CodingKeys: String, CodingKey { 
        case active
        case collectionId
        case createdBy
        case createdOn
        case _id = "id"
        case lastUpdateLogin
        case modifiedBy
        case modifiedOn
        case movie
        case movieId
        case ordering
        case versionNumber
    }


}

