//
// PaymentRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PaymentRequest: Codable {

    public var orderNo: String?
    public var paidAmount: Double?
    public var paymentDate: Date?
    public var paymentMode: String?
    public var paymentStatus: String?
    public var paymentTransactionNo: String?

    public init(orderNo: String?, paidAmount: Double?, paymentDate: Date?, paymentMode: String?, paymentStatus: String?, paymentTransactionNo: String?) {
        self.orderNo = orderNo
        self.paidAmount = paidAmount
        self.paymentDate = paymentDate
        self.paymentMode = paymentMode
        self.paymentStatus = paymentStatus
        self.paymentTransactionNo = paymentTransactionNo
    }


}

