//
// UsernameRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UsernameRequest: Codable {

    public var username: String?

    public init(username: String?) {
        self.username = username
    }


}

