//
// Uploadmovieimage1Body.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Uploadmovieimage1Body: Codable {

    public var file: Data

    public init(file: Data) {
        self.file = file
    }


}
